### ISSUE TITLE
Translate

### ISSUE THREAD

**Issue by AlperAkca79** [jpbandroid/UltraTextEdit-UWP-22H2#10]
I want to help you to translate Turkish. @jpbandroid

**Comment by jpbandroid** [comment]
ok @AlperAkca79 
I will include the translations in release 25236.1000 of the Dev Channel (it should have development started in the next 2 weeks)

**Comment by jpbandroid** [comment]
@AlperAkca79 Have you done the translations yet?
If you haven't it's fine as I can move adding the translations to another build/version of the app

**Comment by AlperAkca79** [comment]
I haven't finished the translation yet. I'll finish until the next build version.

**Comment by AlperAkca79** [comment]
I haven't finished the translation yet. I'll finish until the next build version.

**Comment by jpbandroid** [comment]
ok sure @AlperAkca79 , I will include it in 25252 and 25247
25247 will take me a while to develop because I am going to be adding Tabs to the app
and 25252 will be the same thing without tabs, it will release after the 25247 build

**Comment by AlperAkca79** [comment]
[Drive Link](https://drive.google.com/file/d/1h3dDU-fYcaIwwjeMy7x9qysNZdWFVhZU/view?usp=drivesdk) I have completed the translation.

**Comment by AlperAkca79** [comment]
I have completed the translation. Download link is [here.](https://1drv.ms/u/s!AnFOypuhDP9mvXxuzHn26-UmHNIY?e=tCtYSK)

**Comment by jpbandroid** [comment]
thank you @AlperAkca79 
I'll credit you in the release notes

**Comment by jpbandroid** [comment]
Hello @AlperAkca79 , I still haven't integrated the translation... 😪
But I should in next build (it won't take as long as last time!)
and, I have some ideas for SkyNotepad (I can open them as issue/pull request in its repository)

**Comment by jpbandroid** [comment]
The translation has been integrated into a new build!
It will arrive soon!
(I will still credit you in release notes)
