### ISSUE TITLE
Translate to it-IT

### ISSUE THREAD

**Issue by LuisYeah1234-hub** [jpbandroid/UltraTextEdit-UWP-22H2#11]
Hi im OSBetaEAC i Will try to translate this app by tmrw!

**Comment by jpbandroid** [comment]
ok thx @LuisYeah1234-hub

**Comment by jpbandroid** [comment]
the app is now translated! (as per commit e9d4e3daabcaa444d518742750ecb0ed0af3899c in the dev branch)
I will add more resources for translation in coming releases, so the translation will have to be updated...
