### ISSUE TITLE
Translate to ro-RO

### ISSUE THREAD

**Issue by GrooveMusic10** [jpbandroid/UltraTextEdit-UWP-22H2#12]
Hi! I am Groove and I want to translate!

**Comment by jpbandroid** [comment]
ok @GrooveMusic10 , open the main Resources.resw in Strings/Resources.resw, copy its contents to your PC and translate strings into Romanian.
When you are done, just link your modified file here or submit a pull request with the Romanian-language strings under Strings/ro-RO/Resources.resw
And thank you for translating, and if you want to suggest any ideas to improve the program, don't hesitate to open another issue/pull request!
