### ISSUE TITLE
Clicking on "Check for updates" button on update page crashes the app

### ISSUE THREAD

**Issue by Alloyd031** [jpbandroid/UltraTextEdit-UWP-22H2#21]

**Comment by jpbandroid** [comment]
yes, it does (or it *did*, I fixed the bug some time ago)
Just update to versions 22621.1194 or later or 25201.81 or later
If you're on the Dev Channel or Beta Channel build (to find out which, look at titlebar), then the update service could be broken...
I didn't test yet, but if it is broken, I'll fix it in next release
